/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NavHead: typeof import('./src/components/NavHead.vue')['default']
    NavTitle: typeof import('./src/components/NavTitle.vue')['default']
    NoData: typeof import('./src/components/NoData.vue')['default']
    OrderItem: typeof import('./src/components/OrderItem.vue')['default']
    OrganizerInfo: typeof import('./src/components/OrganizerInfo.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    Record: typeof import('./src/components/Record.vue')['default']
  }
}
